version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ymbox_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ymbox_ai_chat
    restart: unless-stopped

volumes:
  mongodb_data:
    name: ymbox_mongodb_data 